services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
      - pdf_data:/data/raw  
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "9000:9000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  qdrant_data:
    driver: local
  pdf_data:   
    driver: local
